fused:
  graph_node_fusion:
    ros__parameters:
      debug_distance: true
      detection_topic: /filtered/detection_graph_nodes/graph_nodes
      exploitation_topic: /filtered/exploitation_graph_nodes/graph_nodes
      exploration_topic: /filtered/exploration_graph_nodes/graph_nodes
      exploration_weight: 0.5
      fused_topics:
        detection_graph_nodes: detection_graph_nodes/graph_nodes
        exploration_graph_nodes: exploration_graph_nodes/graph_nodes
      timer_period: 0.1
      weights.det_weight: 1.0
      weights.map_weight: 1.0
      weights.mem_sigma: 0.5
      weights.mem_weight: 1.0
      weights.proximity_radius: 5.0
      weights.proximity_weight: 0.2
      weights.source_balance: 0.1
      weights.costmap_weight: 1.0
      weights.costmap_radius: 0.5
      weights.debug_costmap: true


# fused:
#   graph_node_fusion:
#     ros__parameters:
#       exploitation_topic: "/test/exploitation_graph_nodes/graph_nodes"
#       exploration_topic: /test/exploration_graph_nodes/graph_nodes
#       detection_topic: /test/detection_graph_nodes/graph_nodes
#       plan_rate: 0.1
#       approach_radius: 1.5
#       max_visited: 200
#       exploration_weight: 1.0
#       sigma: 1.5
#       gaussian_influence: 0.5
#       sight_horizon: 5.0
#       fused_topics:
#         detection_graph_nodes: "detection_graph_nodes/graph_nodes"
#         exploration_graph_nodes: "exploration_graph_nodes/graph_nodes"